- .github/workflows/publish.yaml
- .goreleaser.yaml
- package/Dockerfile-helm-project-operator
- scripts/build-chart
- scripts/package-helm
- scripts/util-chart
This simply adds the necessary steps so that our debug/dev artifacts for HPO/HL/etc are published with releases.
> Repo reorg follow up for Releases

- package/Dockerfile-prometheus-federator
> stop adding helm to prom-fed images

- .github/workflows/pr-debug-publish.yaml
- .github/workflows/prom-fed-e2e-ci.yaml
will be great to have renovate handle this in the future....
> fix actions with old versions

- .github/scripts/branch-tags.sh
- .github/workflows/e2e/scripts/install-federator.sh
- .github/workflows/e2e/scripts/validate-project-grafana-dashboards.sh
- .github/workflows/e2e/scripts/validate-project-prometheus-alerts.sh
- .github/workflows/e2e/scripts/validate-project-prometheus-targets.sh
- .github/workflows/prom-fed-e2e-ci.yaml
- .github/workflows/publish.yaml
- scripts/local-e2e
- scripts/version
Should fix issue where docker images get tagged incorrectly if a single commit has multiple tags
This seeks to fix situations like: https://github.com/rancher/prometheus-federator/actions/runs/13295121902/job/37126035172
> fix(ci): corrects multiple tags bug & add a `local-ci` script

- docs/helm-locker/developing.md
- docs/helm-project-operator/developing.md
- docs/prometheus-federator/developing.md
Related Issue: #167 
| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring `package.yaml`                  | You modified the contents of the `rancher-project-monitoring` chart to make changes                                                    | Does Not Apply |
| …
> [doc] Adds missing parameters in the docker image test commands

- .github/workflows/e2e/scripts/cluster-args.sh
- .github/workflows/e2e/scripts/create-projecthelmchart.sh
- .github/workflows/e2e/scripts/generate-artifacts.sh
- .github/workflows/e2e/scripts/install-federator.sh
- .github/workflows/e2e/scripts/validate-project-prometheus-alerts.sh
- .github/workflows/lint.yaml
- .github/workflows/prom-fed-e2e-ci.yaml
- build.yaml
- charts/prometheus-federator/values.yaml
- pkg/buildconfig/constants.go
- scripts/build-chart
- scripts/k3s-version
- scripts/local-e2e
Per title this PR complements our Monitoring rebase efforts to implement the same version in Project Monitoring & PromFed part of our stack.
> feat: Update Rancher Project Monitoring to use upstream 66.7.1

- .github/workflows/e2e/scripts/install-monitoring.sh
- .github/workflows/e2e/scripts/validate-project-alertmanager.sh
Specifically this allows things to be passing if: InfoInhibitor and/or PrometheusOutOfOrderTimestamps are also seen.
> Adjust Alertmanager E2E verification to allow common alerts

- .github/renovate.json
- adds gomod deps to renovate targets
- removes legacy branch 0.X from renovate
- matches branches to specific rancher releases
> feat (renovate) : add gomod deps to renovate config

- charts/prometheus-federator/templates/cleanup.yaml
Related Issue: https://github.com/rancher/prometheus-federator/issues/145
> fix(chart): patch clean up job for CRD bug

- build.yaml
- pkg/buildconfig/constants.go
- scripts/util-team-charts
Related Issue: https://github.com/rancher/ob-team-charts/pull/62
> [main] Bump RPM version and generate

- charts/prometheus-federator/templates/deployment.yaml
- charts/prometheus-federator/values.yaml
Backport of: https://github.com/rancher/prometheus-federator/pull/195
> [backport] feat(chart): Add ability to configure PromFed Priority class

- build.yaml
- pkg/buildconfig/constants.go
Related Issue: https://github.com/rancher/ob-team-charts/pull/69
Please fill out this table to identify which fields need to be modified in your PR.
**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.
| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring …
> [v3.x] Update rancher-project-monitoring to 0.6.0

- build.yaml
- pkg/buildconfig/constants.go
Related Issue: https://github.com/rancher/ob-team-charts/pull/69
Please fill out this table to identify which fields need to be modified in your PR.
**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.
| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring …
> [main] Update rancher-project-monitoring to 0.6.0

- internal/helm-project-operator/controllers/namespace/controller.go
- internal/helm-project-operator/controllers/namespace/namespaces.go
Addresses : https://github.com/rancher/prometheus-federator/issues/264
> fix(project-registration) : handle edge cases around resource conflicts

- .github/workflows/e2e/scripts/install-monitoring.sh
- build.yaml
- pkg/buildconfig/constants.go
Related Issue: https://github.com/rancher/rancher/issues/49868
Please fill out this table to identify which fields need to be modified in your PR.
**Under `Status`, either indicate `Does Not Apply` or `Added to this PR`**.
| **Version to be incremented**                                              | Why should this be modified?                                                                                                           | Status                                      |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| `version` in rancher-project-monitoring `package.yaml` …
> V2.x rpm 0.5.2

- charts/prometheus-federator/Chart.yaml
(cherry picked from commit 44a37ffd9d67a4c9f7922eb64e8bdcfe1f4857fd)
> [release/v3.x][backport] fix(chart): correct Icon path to fix rancher/charts air-gap issue

- charts/prometheus-federator/Chart.yaml
(cherry picked from commit 44a37ffd9d67a4c9f7922eb64e8bdcfe1f4857fd)
> [release/v2.x][backport] fix(chart): correct Icon path to fix rancher/charts air-gap issue

- .github/workflows/e2e/scripts/entry
- .github/workflows/e2e/scripts/install-monitoring.sh
- build.yaml
- package/Dockerfile-prometheus-federator
- pkg/buildconfig/constants.go
- scripts/build-chart
- scripts/util-kuberlr
- scripts/util-rpm-chart
- scripts/util-team-charts
- scripts/version
Backport of: https://github.com/rancher/prometheus-federator/pull/280
> [backport][rancher 2.11][monitoring 66.7] ci/build: Fix Rancher Project Monitoring Compatibility Issues (#280)

- .github/workflows/e2e/scripts/entry
- .github/workflows/e2e/scripts/install-monitoring.sh
- build.yaml
- package/Dockerfile-prometheus-federator
- pkg/buildconfig/constants.go
- scripts/build-chart
- scripts/util-kuberlr
- scripts/util-rpm-chart
- scripts/util-team-charts
- scripts/version
Backport of: https://github.com/rancher/prometheus-federator/pull/280
> [backport][rancher 2.9] ci/build: Fix Rancher Project Monitoring Compatibility Issues (#280)

- README.md
- build.yaml
- pkg/buildconfig/constants.go
Related Issue: https://github.com/rancher/prometheus-federator/issues/292
> [main] Bump RPM

- .github/workflows/publish.yaml
- Makefile
Related Issue: https://github.com/rancher/prometheus-federator/issues/304
> Make push-image an explicit make target

- .github/workflows/publish.yaml
Related Issue: https://github.com/rancher/prometheus-federator/issues/304
> [main] Add missing repo checkout step

- .github/workflows/publish.yaml
- Makefile
- scripts/push-image
Related Issue: https://github.com/rancher/prometheus-federator/issues/304
> [main] More CI fixes to enable pushing to Prime registry
